### ISSUE TITLE
입력 값 길이, 토큰 만료 예외처리 추가

### ISSUE THREAD

**Issue by uk960214** [The-Fellowship-of-the-matzip/mat.zip-front#106]
# 기존
입력 값 길이에 대한 예외 처리 누락
토큰 만료 시 시나리오 예외 처리 누락

# 변경
입력 값 예외처리 기준: 메뉴 - 20자, content - 255자
토큰 만료 시나리오: 로그아웃 처리

**Comment by nan-noo** [comment]
이거 해결 됐었군요
