### ISSUE TITLE
컴포넌트 폴더 분리

### ISSUE THREAD

**Issue by nan-noo** [The-Fellowship-of-the-matzip/mat.zip-front#36]
# as-is
모든 컴포넌트가 components 폴더 아래에 있음

# to-be
회의 후 결정
이슈 아래 댓글로 남겨주세요

**Comment by nan-noo** [comment]
## 태태 의견
- components/pages
   - ...Page 컴포넌트
      - ...Item
      - ...Category 등 해당 페이지에서 쓰이는 컴포넌트
- components/layout
   - ...Header 컴포넌트
   - ...Main
   - ...Footer
 - components/common 또는 @shared
    - ...Chip
    - ...Button
    - ...Star

**Comment by uk960214** [comment]
태태가 짱이다 👍
